---
title: "Title"
description: |
  Population affect Response function, SDM, Occurrence
author:
  - name: Cheongok Jeon 
    url: https://github.com/lophital
    affiliation: Seoul National University, Korea
    affiliation_url: https://geog.snu.ac.kr/
    orcid_id: 0000-0002-9950-6794
  - name: Daehyun Kim
    affiliation: Seoul National University, Korea
    affiliation_url: https://geog.snu.ac.kr/
    orcid_id: 0000-0001-9239-5895
twitter: 
  site: "@lophital"
  creator: "@lophital"
journal: 
  title: "Ecography"
  pasge: "1-27"
  # issn: 2490-1752
  # publisher: ESA
# volume: 44
# issue: 4
doi: "10.1002/ecm.1486"
date: "2023-1-1"
bibliography: references.bib
bib-humanities: true
output: 
  distill::distill_article:
    toc: true
    toc_depth: '2'
    theme: theme.css
creative_commons: CC BY
header-includes: 
  \usepackage{caption}
  \renewcommand{\figurename}{Fig.} 
  \renewcommand{\thefigure}{S\arabic{figure}} 
  \renewcommand{\thetable}{S\arabic{table}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center"
)
```

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(virtualspecies)
library(NLMR)
library(raster)
library(spatstat)
library(SDMtune)
library(precrec)
library(Metrics)
library(prg)
```


